import { iconifyHtml } from '../utils.js'

type LogosEntry = string | { key: string; icon: string }

/**
 * List of logos icons used by resumxIconResolver.
 * - String entries use the same value for both input key and icon name
 * - Object entries specify different input key and icon name
 */
const RESUMX_LOGOS_NAMES: readonly LogosEntry[] = [
	// A - Adobe suite & popular services
	'adobe-after-effects',
	'adobe-animate',
	'adobe-dreamweaver',
	'adobe-icon',
	{ key: 'adobe', icon: 'adobe-icon' },
	'adobe-illustrator',
	'adobe-incopy',
	'adobe-indesign',
	'adobe-lightroom',
	'adobe-photoshop',
	'adobe-premiere',
	'adobe-xd',
	'airtable',
	'airbnb-icon',
	{ key: 'airbnb', icon: 'airbnb-icon' },
	'algolia',
	'alpinejs-icon',
	{ key: 'alpinejs', icon: 'alpinejs-icon' },
	'amex-digital',
	{ key: 'amex', icon: 'amex-digital' },
	'anthropic-icon',
	{ key: 'anthropic', icon: 'anthropic-icon' },
	'apple-app-store',
	{ key: 'app-store', icon: 'apple-app-store' },
	'apple-pay',
	'arc',
	'asana-icon',
	{ key: 'asana', icon: 'asana-icon' },
	'atlassian',
	'auth0-icon',
	{ key: 'auth0', icon: 'auth0-icon' },
	'awesome',
	'axios',
	// B
	'bamboo',
	'basecamp-icon',
	{ key: 'basecamp', icon: 'basecamp-icon' },
	'behance',
	'bluetooth',
	'boardcom-icon',
	{ key: 'boardcom', icon: 'boardcom-icon' },
	'brave',
	'browserstack',
	// C
	'calibre-icon',
	{ key: 'calibre', icon: 'calibre-icon' },
	'chai',
	'chef',
	'circleci',
	'claude-icon',
	{ key: 'claude', icon: 'claude-icon' },
	'clickup',
	'cloudflare-icon',
	{ key: 'cloudflare', icon: 'cloudflare-icon' },
	'codecov-icon',
	{ key: 'codecov', icon: 'codecov-icon' },
	'codesandbox-icon',
	{ key: 'codesandbox', icon: 'codesandbox-icon' },
	'contentful',
	// D
	'daisyui-icon',
	{ key: 'daisyui', icon: 'daisyui-icon' },
	'datadog-icon',
	{ key: 'datadog', icon: 'datadog-icon' },
	'datocms-icon',
	{ key: 'datocms', icon: 'datocms-icon' },
	'dbt-icon',
	{ key: 'dbt', icon: 'dbt-icon' },
	'discord-icon',
	{ key: 'discord', icon: 'discord-icon' },
	'django-icon',
	{ key: 'django', icon: 'django-icon' },
	'docusaurus',
	'dribbble-icon',
	{ key: 'dribbble', icon: 'dribbble-icon' },
	'dropbox',
	'duckduckgo',
	// E - F
	'esbuild',
	'fauna-icon',
	{ key: 'fauna', icon: 'fauna-icon' },
	'firefox',
	'fly-io-icon',
	{ key: 'fly', icon: 'fly-io-icon' },
	{ key: 'fly-io', icon: 'fly-io-icon' },
	'framer',
	// G
	'google-analytics',
	'google-calendar',
	'google-drive',
	'google-gemini',
	{ key: 'gemini', icon: 'google-gemini' },
	'google-gmail',
	{ key: 'gmail', icon: 'google-gmail' },
	'google-maps',
	'google-meet',
	'google-photos',
	'google-play-icon',
	{ key: 'google-play', icon: 'google-play-icon' },
	'graphql',
	// H
	'hashicorp-icon',
	{ key: 'hashicorp', icon: 'hashicorp-icon' },
	'headlessui-icon',
	{ key: 'headlessui', icon: 'headlessui-icon' },
	'hubspot',
	// I
	'instagram-icon',
	{ key: 'instagram', icon: 'instagram-icon' },
	'intercom-icon',
	{ key: 'intercom', icon: 'intercom-icon' },
	// J - K - L
	'jasmine',
	'jest',
	'lastfm',
	'launchdarkly-icon',
	{ key: 'launchdarkly', icon: 'launchdarkly-icon' },
	'linear-icon',
	{ key: 'linear', icon: 'linear-icon' },
	'lit',
	'loom-icon',
	{ key: 'loom', icon: 'loom-icon' },
	// M
	'mailchimp',
	'mantine-icon',
	{ key: 'mantine', icon: 'mantine-icon' },
	'mastercard',
	'meta-icon',
	{ key: 'meta', icon: 'meta-icon' },
	'medium-icon',
	{ key: 'medium', icon: 'medium-icon' },
	'meilisearch',
	'microsoft-icon',
	{ key: 'microsoft', icon: 'microsoft-icon' },
	'midjourney',
	'miro-icon',
	{ key: 'miro', icon: 'miro-icon' },
	'mistral-ai-icon',
	{ key: 'mistral-ai', icon: 'mistral-ai-icon' },
	{ key: 'mistral', icon: 'mistral-ai-icon' },
	'mixpanel',
	'monday-icon',
	{ key: 'monday', icon: 'monday-icon' },
	'mozilla',
	// N
	'neon-icon',
	{ key: 'neon', icon: 'neon-icon' },
	'netflix-icon',
	{ key: 'netflix', icon: 'netflix-icon' },
	'nodejs',
	{ key: 'nodejs', icon: 'nodejs-icon' },
	'nomad',
	'notion-icon',
	{ key: 'notion', icon: 'notion-icon' },
	'nx',
	// O
	'obsidian-icon',
	{ key: 'obsidian', icon: 'obsidian-icon' },
	'openai-icon',
	{ key: 'openai', icon: 'openai-icon' },
	// P
	'pagerduty-icon',
	{ key: 'pagerduty', icon: 'pagerduty-icon' },
	'pandacss-icon',
	{ key: 'pandacss', icon: 'pandacss-icon' },
	{ key: 'panda', icon: 'pandacss-icon' },
	'parcel-icon',
	{ key: 'parcel', icon: 'parcel-icon' },
	'paypal',
	'perplexity-icon',
	{ key: 'perplexity', icon: 'perplexity-icon' },
	'pinecone-icon',
	{ key: 'pinecone', icon: 'pinecone-icon' },
	'pinia',
	'pinterest',
	'planetscale',
	'posthog-icon',
	{ key: 'posthog', icon: 'posthog-icon' },
	'prettier',
	'producthunt',
	'puppet',
	// Q - R
	'qwik',
	'radix-ui',
	'react-query-icon',
	{ key: 'react-query', icon: 'react-query-icon' },
	'reddit-icon',
	{ key: 'reddit', icon: 'reddit-icon' },
	// S
	'segment-icon',
	{ key: 'segment', icon: 'segment-icon' },
	'shadcn-ui',
	'shopify',
	'signal',
	'skype',
	'slack-icon',
	{ key: 'slack', icon: 'slack-icon' },
	'snyk',
	'snowflake-icon',
	{ key: 'snowflake', icon: 'snowflake-icon' },
	'soundcloud',
	'splunk',
	'spotify-icon',
	{ key: 'spotify', icon: 'spotify-icon' },
	'steam',
	'stability-ai-icon',
	{ key: 'stability-ai', icon: 'stability-ai-icon' },
	'stackblitz-icon',
	{ key: 'stackblitz', icon: 'stackblitz-icon' },
	'stencil',
	'storyblok-icon',
	{ key: 'storyblok', icon: 'storyblok-icon' },
	'stripe',
	'swc',
	// T
	'teamcity',
	'telegram',
	'testing-library',
	'tiktok-icon',
	{ key: 'tiktok', icon: 'tiktok-icon' },
	'todoist-icon',
	{ key: 'todoist', icon: 'todoist-icon' },
	'travis-ci',
	'turborepo-icon',
	{ key: 'turborepo', icon: 'turborepo-icon' },
	'twitch',
	'twilio-icon',
	{ key: 'twilio', icon: 'twilio-icon' },
	'typeorm',
	// U
	'unocss',
	'upstash-icon',
	{ key: 'upstash', icon: 'upstash-icon' },
	'upwork',
	// V
	'vault',
	'vimeo-icon',
	{ key: 'vimeo', icon: 'vimeo-icon' },
	'visa',
	// W
	'webflow',
	'whatsapp-icon',
	{ key: 'whatsapp', icon: 'whatsapp-icon' },
	'wix',
	// X
	'x',
	// Y
	'yahoo',
	'ycombinator',
	'youtube-icon',
	{ key: 'youtube', icon: 'youtube-icon' },
	// Z
	'zod',
	'zapier',
	'zendesk-icon',
	{ key: 'zendesk', icon: 'zendesk-icon' },
	'zoom',
] as const

/**
 * Builds a name → HTML map for Iconify logos icons.
 * String entries use the value for both key and icon name.
 * Object entries specify different key and icon name (without logos: prefix).
 *
 * @returns Record<string, string> suitable for createCustomResolver or lookup.
 */
function createLogosMap(): Record<string, string> {
	const map: Record<string, string> = {}
	for (const entry of RESUMX_LOGOS_NAMES) {
		if (typeof entry === 'string') {
			map[entry] = iconifyHtml(`logos:${entry}`)
		} else {
			map[entry.key] = iconifyHtml(`logos:${entry.icon}`)
		}
	}
	return map
}

export const logosMap = createLogosMap()
